services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ticket_app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always
    # ports:
    #   - "${POSTGRES_PORT:-5432}:5432"
  cache:
    image: redis
    restart: always
    # image: docker.dragonflydb.io/dragonflydb/dragonfly
    # image: eqalpha/keydb
    # ports:
    #   - "${REDIS_PORT:-6379}:6379"
