services:
  migrator:
    build:
      dockerfile: images/Dockerfile_migrator
    depends_on:
      db:
        condition: service_healthy
        restart: true
      cache:
        condition: service_started
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ticket_app
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
  app:
    build:
      dockerfile: images/Dockerfile_app
    depends_on:
      db:
        condition: service_healthy
        restart: true
      cache:
        condition: service_started
      migrator:
        condition: service_completed_successfully
    environment:
      APP__DATABASE_USERNAME: ${POSTGRES_USER:-user}
      APP__DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-password}
      APP__DATABASE_NAME: ticket_app
    ports:
      - 80:80
