services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
      cache:
        condition: service_started
    environment:
      APP__DATABASE_USERNAME: ${POSTGRES_USER:-user}
      APP__DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-password}
      APP__DATABASE_NAME: ticket_app
    ports:
      - 80:80
