application:
  port: 8000
  host: 0.0.0.0
  auth_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  port: 5432
  database_name: "ticket_app"
  require_ssl: false
redis:
  protocol: resp3
  port: 6379
logging:
  dest: stdout
  enable: true
